---
ipv6_config: enable
disable_wifi: true
disable_bluetooth: true
# ollama-arc specific vars
ollama_arc_models_path: /data/ai/models/ollama-arc # Specific path for ailab host
# ollama_arc_memory: "64G" # Optional: Override default memory if needed
# ollama_arc_shm_size: "32g" # Optional: Override default shm size if needed

# Override config_root specifically for ailab
config_root: /home/{{ username_personal }}/config

# comfyui specific vars
comfyui_storage_path: /home/{{ username_personal }}/comfyui/storage # Specific path for ailab host in user home

# Netplan Static IP Configuration
netplan_interface: "enp12s0" # Verify the correct interface name on your ailab host
netplan_address_cidr: "192.168.50.9/24"
netplan_gateway: "192.168.50.1"
netplan_dns_servers:
  - "192.168.50.4"
  - "192.168.50.5"
# netplan_config_filename: "40-static-ip.yaml" # Optional: only if you want to override the default filename
