---
ipv6_config: enable
disable_wifi: true
disable_bluetooth: true

# Override config_root specifically for ailab
config_root: /home/{{ username_personal }}/config

# comfyui specific vars
comfyui_storage_path: /home/{{ username_personal }}/comfyui/storage # Specific path for ailab host in user home
