---
extends: default

rules:
  # Disable line length check (often problematic for Ansible)
  line-length: disable
  # Increase indentation flexibility slightly if needed
  # indentation:
  #   spaces: 2 # or 4, depending on preference
  #   indent-sequences: consistent # or whatever you prefer

# Ignore vendor roles or specific files/directories
ignore: |
  .venv/
  roles/geerlingguy.*
  # Add other paths to ignore if necessary
  # roles/community.*
