---
- name: Prune Docker Resources
  hosts: all
  become: true

  tasks:
    - name: Prune Docker resources
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
