---
- name: Distribute SSH public key from ailab-ubuntu to all hosts
  hosts: ailab_ubuntus
  gather_facts: no
  become: false

  vars:
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:
    - name: Read SSH public key from ailab-ubuntu
      ansible.builtin.slurp:
        src: ~/.ssh/id_rsa.pub
      register: ssh_public_key_b64

    - name: Set public key as fact
      ansible.builtin.set_fact:
        ssh_public_key: "{{ ssh_public_key_b64['content'] | b64decode }}"

- name: Add SSH public key to all hosts
  hosts: all:!winhost1
  become: yes
  gather_facts: yes

  vars:
    # Get the key from the ailab-ubuntu control node
    ssh_public_key: "{{ hostvars['ailab-ubuntu']['ssh_public_key'] | default(omit) }}"

  tasks:
    - name: Add SSH public key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ ssh_public_key }}"
        exclusive: no
        manage_dir: yes
      when: ssh_public_key is defined

    - name: Display result
      debug:
        msg: "SSH key added to {{ inventory_hostname }} for user {{ ansible_user }}"
      when: ssh_public_key is defined
