---
- name: Distribute SSH public key from ailab-ubuntu to all hosts
  hosts: ailab_ubuntus
  gather_facts: no
  become: false

  vars:
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:
    - name: Read SSH public key
      debug:
        msg: "Public key: {{ ssh_public_key }}"

- name: Add SSH public key to all hosts
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    # Get the key from the ailab-ubuntu control node
    ssh_public_key: "{{ hostvars['ailab-ubuntu']['ssh_public_key'] | default(omit) }}"

  tasks:
    - name: Add SSH public key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "{{ ssh_public_key }}"
        exclusive: no
        manage_dir: yes
      when: ssh_public_key is defined and ansible_facts['distribution'] != 'Windows'

    - name: Display result
      debug:
        msg: "SSH key added to {{ inventory_hostname }} for user {{ ansible_user_id }}"
      when: ssh_public_key is defined and ansible_facts['distribution'] != 'Windows'