---
- name: Get SSH Public Key
  hosts: localhost
  gather_facts: false
  vars:
    source_host: localhost
    source_user: daniel
  tasks:
    - name: Read the public key from {{ source_host }}
      slurp:
        src: /home/{{ source_user }}/.ssh/id_rsa.pub
      register: public_key_content
      delegate_to: "{{ source_host }}"
    - name: Set fact with public key
      set_fact:
        ssh_public_key: "{{ public_key_content.content | b64decode }}"
    - name: Display the public key
      debug:
        var: ssh_public_key
