---
roles:
  - src: geerlingguy.pip
  - src: geerlingguy.docker

collections:
  - name: community.crypto
  - name: community.docker
  - name: community.general
  - name: ansible.posix
  - name: artis3n.tailscale
