---
- hosts: homelab
  #remote_user: root
  roles:
    - { role: nuc, become: yes, tags: ["nuc"] }
    - { role: basic, become: yes, tags: ["basic"] }
    - { role: geerlingguy.pip, become: yes, tags: ["docker"] }
    - { role: geerlingguy.docker, become: yes, tags: ["docker"], vars: { docker_install_compose: true } }
    - { role: dockerhub, become: yes, tags: ["docker", "dockerhub"] }
    - { role: dockerproxy, become: yes, tags: ["docker", "dockerproxy", "portainer"] }
    - { role: portainer, become: yes, tags: ["docker", "portainer"] }

    - { role: storage, become: yes, tags: ["storage"] }
    - { role: homeassistant, become: yes, tags: ["ha"] }
    - { role: fix_hass_bluetooth, become: yes, tags: ["ha"]}
    - { role: media, become: yes, tags: ["media"] }
    - { role: monitoring, become: yes, tags: ["monitoring"] }
    - { role: homepage, become: yes, tags: ["homepage"] }
    - { role: caddy, become: yes, tags: ["caddy"] }
    - { role: resolved, become: yes, tags: ["pihole"] }
    - { role: pihole, become: yes, tags: ["pihole"] }

    #- media
- hosts: nameserver
  roles:
    - { role: pi, become: yes, tags: ["pi"] }
    - { role: basic, become: yes, tags: ["basic"] }
    - { role: geerlingguy.pip, become: yes, tags: ["docker"] }
    - { role: geerlingguy.docker, become: yes, tags: ["docker"], vars: { docker_install_compose: true } }
    - { role: dockerhub, become: yes, tags: ["docker", "dockerhub"] }
    - { role: dockerproxy, become: yes, tags: ["docker", "dockerproxy", "portainer"] }
    - { role: portainer, become: yes, tags: ["docker", "portainer"] }
    - { role: pihole, become: yes, tags: ["pihole"] }

- hosts: ailab
  roles:
    - { role: geerlingguy.pip, become: yes, tags: ["docker"] }
    - { role: geerlingguy.docker, become: yes, tags: ["docker"], vars: { docker_install_compose: true } }
    - { role: dockerhub, become: yes, tags: ["docker", "dockerhub"] }
    - { role: dockerproxy, become: yes, tags: ["docker", "dockerproxy", "portainer"] }
    - { role: portainer, become: yes, tags: ["docker", "portainer"] }

    - { role: ollama, become: yes, tags: ["ollama"]}
    - { role: wolf, become: yes, tags: ["wolf"]}