---
- name: Set up homelab
  hosts: homelab
  roles:
    - { role: nuc, become: true, tags: [nuc] }
    - { role: basic, become: true, tags: [basic] }
    - { role: geerlingguy.pip, become: true, tags: [docker] }
    - { role: geerlingguy.docker, become: true, tags: [docker], vars: { docker_install_compose: true } }
    - { role: dockerhub, become: true, tags: [docker, dockerhub] }
    - { role: dockerproxy, become: true, tags: [docker, dockerproxy, portainer] }
    - { role: portainer, become: true, tags: [docker, portainer] }
    - { role: glances, become: true, tags: [glances] }
    - { role: zfs, become: true, tags: [zfs, storage] }
    - { role: storage, become: true, tags: [storage] }
    - { role: borgmatic, become: true, tags: [borgmatic, backup] }
    - { role: caddy, become: true, tags: [caddy] }
    - { role: trust_internal_ca, become: true, tags: [caddy, ca] }

    - { role: pihole, become: true, tags: [pihole] }
    - { role: homeassistant, become: true, tags: [ha] }
    - { role: fix_hass_bluetooth, become: true, tags: [ha] }
    - { role: babybuddy, become: true, tags: [babybuddy] }
    - { role: media, become: true, tags: [media] }
    - { role: monitoring, become: true, tags: [monitoring] }
    - { role: homepage, become: true, tags: [homepage] }
    - { role: llm_tools, become: true, tags: [llm, llm-tools] }
    - { role: llm_observability, become: true, tags: [llm, llm-observability] }
    - { role: metamcp, become: true, tags: [metamcp] }
    - { role: wallabag, become: true, tags: [wallabag] }
    - { role: readeck, become: true, tags: [readeck] }
    - { role: linkding, become: true, tags: [linkding] }
    - { role: changedetection, become: true, tags: [changedetection] }
    - { role: immich, become: true, tags: [immich] }
    - { role: teslamate, become: true, tags: [teslamate] }
    - { role: n8n, become: true, tags: [n8n] }
    - { role: prunemate, become: true, tags: [prunemate] }

- name: Setup nameserver
  hosts: nameserver
  roles:
    - { role: pi, become: true, tags: [pi] }
    - { role: basic, become: true, tags: [basic] }
    - { role: geerlingguy.pip, become: true, tags: [docker] }
    - { role: geerlingguy.docker, become: true, tags: [docker], vars: { docker_install_compose: true } }
    - { role: dockerhub, become: true, tags: [docker, dockerhub] }
    - { role: dockerproxy, become: true, tags: [docker, dockerproxy, portainer] }
    - { role: trust_internal_ca, become: true, tags: [caddy, ca] }
    - { role: portainer, become: true, tags: [docker, portainer] }
    - { role: glances, become: true, tags: [glances] }
    - { role: pihole, become: true, tags: [pihole] }

- name: Setup virtualhere Pi
  hosts: virtualhere
  ignore_unreachable: true
  roles:
    - { role: pi, become: true, tags: [pi] }
    - { role: basic, become: true, tags: [basic] }
    - { role: geerlingguy.pip, become: true, tags: [docker] }
    - { role: geerlingguy.docker, become: true, tags: [docker], vars: { docker_install_compose: true } }
    - { role: dockerhub, become: true, tags: [docker, dockerhub] }
    - { role: dockerproxy, become: true, tags: [docker, dockerproxy, portainer] }
    - { role: glances, become: true, tags: [glances] }
    - { role: virtualhere, become: true, tags: [virtualhere] }

- name: Setup ailabs
  hosts: ailab_ubuntus
  ignore_unreachable: true
  roles:
    - { role: basic, become: true, tags: [basic] }
    - { role: netplan-static-ip, become: true, tags: [netplan, network] }
    - { role: geerlingguy.pip, become: true, tags: [docker] }
    - { role: geerlingguy.docker, become: true, tags: [docker], vars: { docker_install_compose: true } }
    - { role: dockerhub, become: true, tags: [docker, dockerhub] }
    - { role: dockerproxy, become: true, tags: [docker, dockerproxy, portainer] }
    - { role: portainer, become: true, tags: [docker, portainer] }
    - { role: gpu, become: true, tags: [gpu, gpu-driver] }
    - { role: glances, become: true, tags: [glances], vars: { glances_nvidia_support: true } }
    - { role: trust_internal_ca, become: true, tags: [caddy, ca] }

    #- { role: autosuspend, become: true, tags: [autosuspend] }
    #- { role: intel_gpu_driver, become: true, tags: [intel-gpu, gpu-driver] }
    - { role: llm_inference, become: true, tags: [llm, llm-inference] }
    - { role: wolf, become: true, tags: [wolf] }
    - { role: draw_things, become: true, tags: [draw-things] }
    - { role: comfyui, become: true, tags: [comfyui] }
    - { role: immich_ml, become: true, tags: [immich, immich-ml] }
    - { role: wyoming_openai, become: true, tags: [wyoming-openai] }
    - { role: syncthing, become: true, tags: [syncthing] }

- name: Setup SSH key distribution
  hosts: ailab_ubuntus,homelab,nameserver,proxmox,mic_satellites
  ignore_unreachable: true
  vars:
    source_host: ailab-ubuntu
    source_user: daniel
  roles:
    - { role: ssh_keys, become: true, tags: [ssh-keys] }
