---
- hosts: homelab
  #remote_user: root
  roles:
    - { role: nuc, become: yes, tags: ["nuc"] }
    - { role: basic, become: yes, tags: ["basic"] }
    - { role: geerlingguy.pip, become: yes, tags: ["docker"] }
    - { role: geerlingguy.docker, become: yes, tags: ["docker"], vars: { docker_install_compose: true } }
    - { role: dockercleanup, become: yes, tags: ["docker"] }
    - { role: dockerhub, become: yes, tags: ["docker", "dockerhub"] }
    - { role: dockerproxy, become: yes, tags: ["docker", "dockerproxy", "portainer"] }
    - { role: portainer, become: yes, tags: ["docker", "portainer"] }
    - { role: glances, become: yes, tags: ["glances"] }

    - { role: storage, become: yes, tags: ["storage"] }
    - { role: homeassistant, become: yes, tags: ["ha"] }
    - { role: babybuddy, become: yes, tags: ["babybuddy"] }
    - { role: fix_hass_bluetooth, become: yes, tags: ["ha"]}
    - { role: wyoming, become: yes, tags: ["wyoming"] }
    - { role: media, become: yes, tags: ["media"] }
    - { role: monitoring, become: yes, tags: ["monitoring"] }
    - { role: homepage, become: yes, tags: ["homepage"] }
    - { role: caddy, become: yes, tags: ["caddy"] }
    - { role: resolved, become: yes, tags: ["pihole"] }
    - { role: pihole, become: yes, tags: ["pihole"] }
    - { role: ollama, become: yes, tags: ["ollama"]}

    #- media
- hosts: nameserver
  roles:
    - { role: pi, become: yes, tags: ["pi"] }
    - { role: basic, become: yes, tags: ["basic"] }
    - { role: geerlingguy.pip, become: yes, tags: ["docker"] }
    - { role: geerlingguy.docker, become: yes, tags: ["docker"], vars: { docker_install_compose: true } }
    - { role: dockercleanup, become: yes, tags: ["docker"] }
    - { role: dockerhub, become: yes, tags: ["docker", "dockerhub"] }
    - { role: dockerproxy, become: yes, tags: ["docker", "dockerproxy", "portainer"] }
    - { role: portainer, become: yes, tags: ["docker", "portainer"] }
    - { role: glances, become: yes, tags: ["glances"] }
    - { role: pihole, become: yes, tags: ["pihole"] }

- hosts: virtualhere
  ignore_unreachable: true
  roles:
    - { role: pi, become: yes, tags: ["pi"] }
    - { role: basic, become: yes, tags: ["basic"] }
    - { role: geerlingguy.pip, become: yes, tags: ["docker"] }
    - { role: geerlingguy.docker, become: yes, tags: ["docker"], vars: { docker_install_compose: true } }
    - { role: dockercleanup, become: yes, tags: ["docker"] }
    - { role: dockerhub, become: yes, tags: ["docker", "dockerhub"] }
    - { role: dockerproxy, become: yes, tags: ["docker", "dockerproxy", "portainer"] }
    - { role: glances, become: yes, tags: ["glances"] }
    - { role: virtualhere, become: yes, tags: ["virtualhere"] }

- hosts: ailab
  roles:
    - { role: basic, become: yes, tags: ["basic"] }
    - { role: disable_radios, become: yes, tags: ["radios"] }
    - { role: geerlingguy.pip, become: yes, tags: ["docker"] }
    - { role: geerlingguy.docker, become: yes, tags: ["docker"], vars: { docker_install_compose: true } }
    - { role: dockercleanup, become: yes, tags: ["docker"] }
    - { role: dockerhub, become: yes, tags: ["docker", "dockerhub"] }
    - { role: dockerproxy, become: yes, tags: ["docker", "dockerproxy", "portainer"] }
    - { role: portainer, become: yes, tags: ["docker", "portainer"] }
    - { role: glances, become: yes, tags: ["glances"] }

    - { role: dmotte.disable_ipv6, become: yes, tags: ["ipv6"] }
    - { role: ollama, become: yes, tags: ["ollama"]}
    - { role: wolf, become: yes, tags: ["wolf"]}

- hosts: mic-satellites
  roles:
    - { role: pi, become: yes, tags: ["pi"] }
    - { role: basic, become: yes, tags: ["basic"] }
    - { role: geerlingguy.pip, become: yes, tags: ["docker"] }
    - { role: geerlingguy.docker, become: yes, tags: ["docker"], vars: { docker_install_compose: true } }
    - { role: dockercleanup, become: yes, tags: ["docker"] }
    - { role: dockerhub, become: yes, tags: ["docker", "dockerhub"] }
    - { role: dockerproxy, become: yes, tags: ["docker", "dockerproxy", "portainer"] }
    - { role: glances, become: yes, tags: ["glances"] }
    - { role: satellite-audio, become: yes, tags: ["wyoming", "satellite-audio"] }
    - { role: cli-visualizer, become: yes, tags: ["vis"] }
