---
- hosts: pi4
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
  remote_user: pi
  roles:
    - basic
    - { role: geerlingguy.pip, become: yes, tags: ["docker"] }
    - { role: geerlingguy.docker_arm, become: yes, tags: ["docker"] }
    - { role: portainer, become: yes, tags: ["docker", "portainer"] }

    - { role: timemachine, become: yes, tags: ["tm"] }
    - { role: homeassistant, become: yes, tags: ["ha"] }
    - { role: pihole, become: yes, tags: ["pihole"] }

    #- media
