---
- name: Set up homelab
  hosts: homelab
  roles:
    - { role: nuc, become: true, tags: [nuc] }
    - { role: basic, become: true, tags: [basic] }
    - { role: geerlingguy.pip, become: true, tags: [docker] }
    - { role: geerlingguy.docker, become: true, tags: [docker], vars: { docker_install_compose: true } }
    - { role: dockercleanup, become: true, tags: [docker] }
    - { role: dockerhub, become: true, tags: [docker, dockerhub] }
    - { role: dockerproxy, become: true, tags: [docker, dockerproxy, portainer] }
    - { role: portainer, become: true, tags: [docker, portainer] }
    - { role: glances, become: true, tags: [glances] }
    - { role: storage, become: true, tags: [storage] }
    - { role: homeassistant, become: true, tags: [ha] }
    - { role: babybuddy, become: true, tags: [babybuddy] }
    - { role: fix_hass_bluetooth, become: true, tags: [ha] }
    - { role: wyoming, become: true, tags: [wyoming] }
    - { role: media, become: true, tags: [media] }
    - { role: monitoring, become: true, tags: [monitoring] }
    - { role: homepage, become: true, tags: [homepage] }
    - { role: caddy, become: true, tags: [caddy] }
    - { role: trust-internal-ca, become: true, tags: [caddy, ca] }
    - { role: resolved, become: true, tags: [pihole] }
    - { role: pihole, become: true, tags: [pihole] }
    - { role: ollama, become: true, tags: [ollama] }

- name: Setup nameserver
  hosts: nameserver
  roles:
    - { role: pi, become: true, tags: [pi] }
    - { role: basic, become: true, tags: [basic] }
    - { role: geerlingguy.pip, become: true, tags: [docker] }
    - { role: geerlingguy.docker, become: true, tags: [docker], vars: { docker_install_compose: true } }
    - { role: dockercleanup, become: true, tags: [docker] }
    - { role: dockerhub, become: true, tags: [docker, dockerhub] }
    - { role: dockerproxy, become: true, tags: [docker, dockerproxy, portainer] }
    - { role: trust-internal-ca, become: true, tags: [caddy, ca] }
    - { role: portainer, become: true, tags: [docker, portainer] }
    - { role: glances, become: true, tags: [glances] }
    - { role: pihole, become: true, tags: [pihole] }

- name: Setup virtualhere Pi
  hosts: virtualhere
  ignore_unreachable: true
  roles:
    - { role: pi, become: true, tags: [pi] }
    - { role: basic, become: true, tags: [basic] }
    - { role: geerlingguy.pip, become: true, tags: [docker] }
    - { role: geerlingguy.docker, become: true, tags: [docker], vars: { docker_install_compose: true } }
    - { role: dockercleanup, become: true, tags: [docker] }
    - { role: dockerhub, become: true, tags: [docker, dockerhub] }
    - { role: dockerproxy, become: true, tags: [docker, dockerproxy, portainer] }
    - { role: glances, become: true, tags: [glances] }
    - { role: virtualhere, become: true, tags: [virtualhere] }

- name: Setup ailabs
  hosts: ailabs
  roles:
    - { role: basic, become: true, tags: [basic] }
    - { role: geerlingguy.pip, become: true, tags: [docker] }
    - { role: geerlingguy.docker, become: true, tags: [docker], vars: { docker_install_compose: true } }
    - { role: dockercleanup, become: true, tags: [docker] }
    - { role: dockerhub, become: true, tags: [docker, dockerhub] }
    - { role: dockerproxy, become: true, tags: [docker, dockerproxy, portainer] }
    - { role: portainer, become: true, tags: [docker, portainer] }
    - { role: glances, become: true, tags: [glances] }

    - { role: intel-gpu-driver, become: true, tags: [intel-gpu, gpu-driver] }
    - { role: ollama-arc, become: true, tags: [ollama-arc] }
    - { role: wolf, become: true, tags: [wolf] }
    - { role: comfyui, become: true, tags: [comfyui] }
    - { role: autosuspend, become: true, tags: [autosuspend] }

- name: Setup mic sattelites
  hosts: mic-satellites
  ignore_unreachable: true
  roles:
    - { role: pi, become: true, tags: [pi] }
    - { role: basic, become: true, tags: [basic] }
    - { role: geerlingguy.pip, become: true, tags: [docker] }
    - { role: geerlingguy.docker, become: true, tags: [docker], vars: { docker_install_compose: true } }
    - { role: dockercleanup, become: true, tags: [docker] }
    - { role: dockerhub, become: true, tags: [docker, dockerhub] }
    - { role: dockerproxy, become: true, tags: [docker, dockerproxy, portainer] }
    - { role: glances, become: true, tags: [glances] }
    - { role: satellite-audio, become: true, tags: [wyoming, satellite-audio] }
    - { role: cli-visualizer, become: true, tags: [vis] }
    - { role: trust-internal-ca, become: true, tags: [caddy, ca] }
