---
- hosts: pi4
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
    router_ip: "192.168.50.1"
    cidr: "192.168.50.0/24"
    pihole_http_port: 81
    portainer_http_port: 9000
    homeassistant_http_port: 8123
    vscode_http_port: 8443
    nodered_http_port: 1880
    mosquitto_port: 1883
    mosquitto_websockets_port: 9001
    z2m_http_port: 8080
    octopi_address: 192.168.50.55
    octopi_http_port: 80
    homeassistant_config_folder: "/media/Medien/home-assistant"
    vscode_config_folder: "/media/Medien/vscode"
    nodered_config_folder: "/media/Medien/node-red"
    mosquitto_config_folder: "/media/Medien/mosquitto/config"
    mosquitto_data_folder: "/media/Medien/mosquitto/data"
    mosquitto_log_folder: "/media/Medien/mosquitto/log"
    zigbee2mqtt_data_folder: "/media/Medien/z2m"
    pihole_config_folder: "/media/Medien/pihole"
    caddy_folder: "/media/Medien/caddy"
    caddy_data_folder: "/media/Medien/caddy/data"
    caddy_config_folder: "/media/Medien/caddy/config"

  remote_user: pi
  roles:
    - basic
    - { role: geerlingguy.pip, become: yes, tags: ["docker"] }
    - { role: geerlingguy.docker_arm, become: yes, tags: ["docker"] }
    - { role: portainer, become: yes, tags: ["docker", "portainer"] }

    - { role: timemachine, become: yes, tags: ["tm"] }
    - { role: homeassistant, become: yes, tags: ["ha"] }
    - { role: caddy, become: yes, tags: ["caddy"] }
    - { role: pihole, become: yes, tags: ["pihole"] }

    #- media
