---
- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 600 # Time in seconds to wait for the system to come back online

- name: Reload udev
  ansible.builtin.command: udevadm control --reload-rules
- name: Trigger udev # ai! add changed_when
  ansible.builtin.command: udevadm trigger
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart PulseAudio
  ansible.builtin.service:
    name: pulseaudio
    state: restarted
