---
- name: Update apt cache and install prerequisites
  become: true
  ansible.builtin.apt:
    name: software-properties-common
    state: present
    update_cache: true

- name: Add Intel Graphics PPA repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:kobuk-team/intel-graphics
    state: present
    update_cache: true # Update cache after adding repo

- name: Install essential Intel compute packages
  become: true
  ansible.builtin.apt:
    name:
      - libze-intel-gpu1
      - libze1
      - intel-metrics-discovery
      - intel-opencl-icd
      - clinfo
      - intel-gsc
    state: present

- name: Install essential Intel media packages
  become: true
  ansible.builtin.apt:
    name:
      - intel-media-va-driver-non-free
      - libmfx1
      - libmfx-gen1
      - libvpl2
      - libvpl-tools
      - libva-glx2
      - va-driver-all
      - vainfo
    state: present

# Optional packages based on variables (define these vars elsewhere)
- name: Install PyTorch specific Intel packages (optional)
  become: true
  ansible.builtin.apt:
    name:
      - libze-dev
      - intel-ocloc
    state: present
  when: install_pytorch_deps | default(false)

- name: Install Intel ray tracing package (optional)
  become: true
  ansible.builtin.apt:
    name: intel-level-zero-gpu-raytracing
    state: present
  when: install_raytracing_deps | default(false)

- name: Ensure render group exists
  become: true
  ansible.builtin.group:
    name: render
    state: present

- name: Add user {{ ansible_user }} to render group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}" # Or specify a different user if needed
    groups: render
    append: true
  notify: Reboot system # User needs to log out/in or reboot for group change to take effect

- name: Ensure handlers are flushed if changes were made
  ansible.builtin.meta: flush_handlers
