---

# AI! add below as ansible
# Refresh the local package index and install the package for managing software repositories.

# apt-get update
# apt-get install -y software-properties-common
# Add the intel-graphics PPA.

# add-apt-repository -y ppa:kobuk-team/intel-graphics
# Install the compute-related packages.

# apt-get install -y libze-intel-gpu1 libze1 intel-metrics-discovery intel-opencl-icd clinfo intel-gsc
# Install the media-related packages.

# apt-get install -y intel-media-va-driver-non-free libmfx1 libmfx-gen1 libvpl2 libvpl-tools libva-glx2 va-driver-all vainfo
# The commands listed above install all the essential packages needed for most users, aiming to minimize the installation of unnecessary packages. However, if you plan to use PyTorch, install libze-dev and intel-ocloc additionally:

# apt-get install -y libze-dev intel-ocloc
# If you wish to enable hardware ray tracing support, install intel-level-zero-gpu-raytracing additionally:

# apt-get install -y intel-level-zero-gpu-raytracing

- name: Ensure render group exists
  become: true
  ansible.builtin.group:
    name: render
    state: present

- name: Add user {{ ansible_user }} to render group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}" # Or specify a different user if needed
    groups: render
    append: true
  notify: Reboot system # User needs to log out/in or reboot for group change to take effect

- name: Ensure handlers are flushed if changes were made
  ansible.builtin.meta: flush_handlers
