---
- ansible.builtin.template:
    src: docker-prune.service.j2
    dest: /etc/systemd/system/docker-prune.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd daemon
- ansible.builtin.template:
    src: docker-prune.timer.j2
    dest: /etc/systemd/system/docker-prune.timer
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd daemon
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Enable and start docker pruning timer
  ansible.builtin.systemd_service:
    name: docker-prune.timer
    state: started
    enabled: true
