- template:
    src: docker-prune.service.j2
    dest: /etc/systemd/system/docker-prune.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd daemon
- template:
    src: docker-prune.timer.j2
    dest: /etc/systemd/system/docker-prune.timer
    owner: root
    group: root
    mode: 0644
  notify: reload systemd daemon
- name: Flush handlers
  meta: flush_handlers
- name: Enable and start docker pruning timer
  ansible.builtin.systemd_service:
    name: docker-prune.timer
    state: started
    enabled: true
