- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes

- apt:
    pkg:
    - samba
    - avahi-daemon

- name: create tm user
  ansible.builtin.user:
    name: tm
    groups: users

- name: create folder for dreifuenf mountpoint
  file: path=/media/tm state=directory

- name: Mount dreifuenf
  mount:
    path: /media/dreifuenf
    src: LABEL=dreifuenf
    fstype: ext4
    opts: noquota
    state: mounted

- name: create folder for share
  file: path=/media/dreifuenf/tm/ state=directory

- name: Reposess tm
  ansible.builtin.file:
    path: /media/dreifuenf/tm
    owner: tm
    group: users
    recurse: yes

- name: create folder for Medien mountpoint
  file: path=/media/Medien state=directory

- name: Mount Medien
  mount:
    path: /media/Medien
    src: LABEL=Medien
    fstype: ext4
    opts: noquota
    state: mounted

- name: Reposess Medien
  ansible.builtin.file:
    path: /media/Medien
    owner: tm
    group: users
    mode: 02775
    recurse: yes

- name: configure tm samba share
  template:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
  notify: reload smb

- name: samba.service
  become: yes
  template:
    src: samba.service
    dest: /etc/avahi/services/samba.service
    owner: root
    group: root
  notify: reload netatalk