- name: Create volume
  community.docker.docker_volume:
    name: ollama_data

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: ollama_build
  register: build_dir

- name: Copy Dockerfile to build directory
  ansible.builtin.copy:
    src: "{{ role_path }}/Dockerfile.mcp-proxy"
    dest: "{{ build_dir.path }}/Dockerfile.mcp-proxy"
    mode: '0644'


- name: Start AI containers
  community.docker.docker_compose_v2:
    project_name: ai
    pull: "always"  # Keep setting for other images
    state: present
    build:  # Build images with missing local ones
      path: "{{ build_dir.path }}"
    definition:
      services:
        ollama-service:
          image: ollama/ollama
          container_name: ollama
          restart: unless-stopped
          ports:
            - "11435:11434"
          environment:
            OLLAMA_DEBUG: "1"
            OLLAMA_NUM_PARALLEL: "2"
            OLLAMA_MAX_LOADED_MODELS: "2"
          volumes:
            - ollama_data:/root/.ollama
          labels:
            wud.tag.include: '^\d+\.\d+\.\d+$$'

        open-webui:
          image: ghcr.io/open-webui/open-webui:main
          container_name: open-webui
          restart: unless-stopped
          environment:
            OLLAMA_BASE_URL: "http://ollama-raw.lan:11434"
          volumes:
            - open-webui:/app/backend/data
          ports:
            - "{{ open_webui_http_port }}:8080"
          labels:
            wud.tag.include: 'main'
            wud.watch.digest: 'true'
            homepage.group: "{{ services['open-webui'].group }}"
            homepage.name: "{{ services['open-webui'].name }}"
            homepage.href: "https://ollama.lan"
            homepage.icon: openai.png
            homepage.server: "{{ inventory_hostname }}"
            homepage.container: open-webui

        todoist-mcp-server:
          image: mcp-base:latest  # Prove this is already built
          build:
            context: "{{ build_dir.path }}"
            dockerfile: Dockerfile.mcp-proxy
          container_name: todoist-mcp-server
          restart: unless-stopped
          command: sh -c "uvx mcp-proxy --sse-port={{ todoist_mcp_proxy_port }} -- npx -y @chrusic/todoist-mcp-server-extended"
          environment:
            TODOIST_API_TOKEN: "{{ todoist_api_token }}"
          ports:
            - "{{ todoist_mcp_proxy_port }}:{{ todoist_mcp_proxy_port }}"
          labels:
            homepage.group: "AI Services"
            homepage.name: Todoist MCP Server
            homepage.href: "http://{{ inventory_hostname }}:{{ todoist_mcp_proxy_port }}"
            homepage.icon: todoist.png
            homepage.server: "{{ inventory_hostname }}"
            homepage.container: todoist-mcp-server

      volumes:
        ollama_data:
          external: true  # External volume for persistent data
        open-webui: {}  # Internal volume for web UI data
