---
# handlers file for llm_inference

- name: Restart llama-swap
  ansible.builtin.command:
    argv:
      - docker
      - restart
      - "{{ llamaswap_container_name }}"
  changed_when: true
  become: true
