
- name: create folders
  file: path={{item}} state=directory owner={{username}}
  with_items:
  - "{{homepage_config_folder}}"

- name: Copy all templates to destination
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{homepage_config_folder}}/{{ item | basename | regex_replace('.j2','') }}"
  loop: "{{ lookup('fileglob', 'templates/*.j2', wantlist=True) }}"

- name: Create network
  docker_network:
    name: homepage
    state: present

- name: Start homepage
  community.docker.docker_compose:
    project_name: homepage
    pull: yes
    definition:
      version: '3.3'
      networks:
        dockerproxy:
          external: true
        homepage:
          external: true
      services:
        homepage:
          image: ghcr.io/gethomepage/homepage:latest
          container_name: homepage
          privileged: true
          environment:
            PUID: "{{uid}}"
            PGID: "{{uid}}"
          dns:
            - "{{ nameserver_pi_ip }}"
            - "{{ homelab_nuc_ip }}"
          ports:
            - "{{homepage_http_port}}:3000"
          volumes:
            - "{{homepage_config_folder}}:/app/config"
            - /var/run/docker.sock:/var/run/docker.sock:ro
          restart: unless-stopped
          networks:
            - dockerproxy
            - homepage
          labels: 
            - wud.tag.include=^v\d+\.\d+\.\d+$$
  register: output

- ansible.builtin.debug:
    var: output

- ansible.builtin.assert:
    that:
      - "output.services.homepage.homepage.state.running"