---
- name: Create folders
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(username) }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - path: "{{ uptime_kuma_data_folder }}"
    - path: "{{ dockhand_data_folder }}"

- name: Start monitoring
  community.docker.docker_compose_v2:
    project_name: monitoring
    pull: always # Set to "always", "missing", "never", or "policy" based on your needs
    state: present # Ensure the services are started
    definition:
      services:
        uptime_kuma:
          image: louislam/uptime-kuma:2
          container_name: uptime_kuma
          ports:
            - "{{ uptime_kuma_http_port }}:3001"
          restart: always
          volumes:
            - "{{ uptime_kuma_data_folder }}:/app/data"
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro # Mount host CA bundle
            - /usr/local/share/ca-certificates/caddy_local_root.crt:/etc/ssl/certs/caddy_local_root.crt:ro
          dns:
            - "{{ nameserver_pi_ip }}"
            - "{{ homelab_nuc_ip }}"
          environment:
            NODE_EXTRA_CA_CERTS: /etc/ssl/certs/caddy_local_root.crt
          network_mode: bridge
          labels:
            homepage.group: "{{ services.uptime.group }}"
            homepage.name: "{{ services.uptime.name }}"
            homepage.href: https://{{ services.uptime.domain }}
            homepage.icon: mdi-server
            homepage.server: "{{ inventory_hostname }}"
            homepage.container: uptime_kuma

        dockhand:
          image: fnsys/dockhand:latest
          container_name: dockhand
          restart: unless-stopped
          ports:
            - "{{ dockhand_http_port }}:3000"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - "{{ dockhand_data_folder }}:/app/data"
          labels:
            homepage.group: "{{ services.dockhand.group }}"
            homepage.name: "{{ services.dockhand.name }}"
            homepage.href: https://{{ services.dockhand.domain }}
            homepage.icon: mdi-docker
            homepage.server: "{{ inventory_hostname }}"
            homepage.container: dockhand

  register: output

- ansible.builtin.debug:
    var: output

- ansible.builtin.assert:
    that:
      - output.containers | selectattr('Name', 'equalto', 'uptime_kuma') | map(attribute='State') | list | first == 'running'
      - output.containers | selectattr('Name', 'equalto', 'dockhand') | map(attribute='State') | list | first == 'running'
