- name: Reboot
  reboot:
    reboot_timeout: 600   # Time in seconds to wait for the system to come back online

- name: Reload udev
  command: udevadm control --reload-rules

- name: Trigger udev
  command: udevadm trigger

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart PulseAudio
  service:
    name: pulseaudio
    state: restarted