- hostname:
    name: pi
  become: yes
  register: hostname
- name: /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1	pi"
    state: "present"
  register: hosts
- reboot:
  when: hostname.changed or hosts.changed
  become: yes
- name: /etc/locale.gen
  become: yes
  lineinfile:
    dest: /etc/locale.gen
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { regexp: '^#? ?de_DE.UTF-8 UTF-8', line: 'de_DE.UTF-8 UTF-8', state: present }
    - { regexp: '^#? ?en_US.UTF-8 UTF-8', line: 'en_US.UTF-8 UTF-8', state: present }
  notify:
    - rebuild locales database
- name: /etc/default/locale
  become: yes
  lineinfile:
    dest: /etc/default/locale
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { regexp: '^LANG=', line: 'LANG=en_US.UTF-8', state: present }
    - { regexp: '^LC_ALL=', line: 'LC_ALL=en_US.UTF-8', state: present }
    - { regexp: '^LANGUAGE=', line: 'LANGUAGE=en_US.UTF-8', state: present }
  notify:
    - rebuild locales database
