---
- name: Install cli-visualizer dependencies
  ansible.builtin.apt:
    name:
      - libfftw3-dev
      - libncursesw5-dev
      - cmake
      - libpulse-dev
    state: present
    update_cache: true

- name: Clone cli-visualizer repo
  ansible.builtin.git:
    repo: https://github.com/dpayne/cli-visualizer.git
    dest: /home/daniel/cli-visualizer
  become_user: daniel
  register: cli_visualizer_repo

- name: Build cli-visualizer
  ansible.builtin.shell: cd /home/daniel/cli-visualizer && ENABLE_PULSE=1 ./install.sh
  become_user: daniel
  when: cli_visualizer_repo.changed

- name: Get pulseaudio source list
  ansible.builtin.shell: pactl list sources short | grep 'alsa_input.usb-0b0e_Jabra_SPEAK_510_USB_745C4B6665B1021800-00.mono-fallback'
  register: result

- name: Extract the index from the source list
  ansible.builtin.set_fact:
    source_index: "{{ (result.stdout.split()[0] | string) }}"

- ansible.builtin.debug:
    var: source_index

- name: Configure cli-visualizer for pulse audio
  ansible.builtin.lineinfile:
    path: /home/daniel/.config/vis/config
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^\\s*#*\\s*audio.sources="
      line: "audio.sources=pulse"
    - regexp: "^\\s*#*\\s*audio.pulse.source="
      line: "audio.pulse.source={{ source_index }}"
