---
- name: Disable stubresolver
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "^#?DNSStubListener="
    line: DNSStubListener=no
  notify: restart resolved

- name: Follow system netplan
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
  notify: restart resolved

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
