- name: Reboot
  reboot:
    reboot_timeout: 600   # Time in seconds to wait for the system to come back online
  become: yes

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart PulseAudio
  service:
    name: pulseaudio
    state: restarted
  become: yes