---
- name: Restart vLLM container
  community.docker.docker_container:
    name: "ipex-llm-serving-xpu-container"
    state: started # Use 'restarted' state here
    restart: true
  become: true

- name: Restart MCP-Bridge container
  community.docker.docker_container:
    name: "{{ mcp_bridge_container_name }}"
    state: started
    restart: true
  become: true

- name: Restart LiteLLM Proxy container
  community.docker.docker_container:
    name: "{{ litellm_proxy_container_name }}" # This variable is defined in defaults/main.yml
    state: started # Ensures the container is running
    restart: true # Forces a restart if the container is already running
  become: true
