---
- name: Restart Ollama container
  community.docker.docker_container:
    name: "{{ ollama_container_name }}"
    state: started
    restart: true
  become: true

- name: Restart MCP-Bridge container
  community.docker.docker_container:
    name: "{{ mcp_bridge_container_name }}"
    state: started
    restart: true
  become: true

- name: Restart LiteLLM Proxy container
  community.docker.docker_container:
    name: "{{ litellm_proxy_container_name }}"
    state: started
    restart: true
  become: true
