FROM yanwk/comfyui-boot:xpu

RUN pip uninstall -y intel-extension-for-pytorch oneccl_bind_pt torch torchvision torchaudio
RUN pip install torch=={{ comfyui_torch_version }} torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/xpu
