- name: Install ALSA utilities
  package:
    name: alsa-utils
    state: latest

- name: Install LADSPA SDK
  package:
    name: ladspa-sdk
    state: latest

- name: Install SWH plugins
  package:
    name: swh-plugins
    state: latest

- name: Install Tap plugins
  package:
    name: tap-plugins
    state: latest

- name: Copy /etc/asound.conf
  template:
    src: alsa.conf
    dest: /etc/asound.conf
  tags:
    - alsa

- name: Ensure the destination directory exists
  file:
    path: "/opt/{{item}}/"
    state: directory
  with_items: 
    - sounds
    - wakewords

- name: Copy sound files to the host
  copy:
    src: "{{ item }}"
    dest: "/opt/sounds/{{ item | basename }}"
  with_fileglob:
    - "sounds/*"

- name: Copy wake word files to the host
  copy:
    src: "{{ item }}"
    dest: "/opt/wakewords/{{ item | basename }}"
  with_fileglob:
    - "wakewords/*"

- name: Start wyoming stack
  tags: alsa
  community.docker.docker_compose_v2:
    project_name: wyoming-stack
    definition:
      version: '3.9'
      services:
        microphone:
          build: https://github.com/rhasspy/wyoming-mic-external.git
          container_name: wyoming-mic-external
          restart: unless-stopped
          ports:
            - "10600:10600"
          volumes:
            - /run/dbus:/run/dbus:ro
            - /etc/asound.conf:/etc/asound.conf:ro
          devices:
            - /dev/snd:/dev/snd
          group_add:
            - audio
          command:
            - "--device"
            - "default"
            - "--debug"
        playback:
          build: https://github.com/rhasspy/wyoming-snd-external.git
          container_name: wyoming-snd-external
          restart: unless-stopped
          ports:
            - "10601:10601"
          volumes:
            - /run/dbus:/run/dbus:ro
            - /etc/asound.conf:/etc/asound.conf:ro
          devices:
            - /dev/snd:/dev/snd
          group_add:
            - audio
          command:
            - --debug
            - --device
            - default
        vader-playback:
          build: https://github.com/rhasspy/wyoming-snd-external.git
          container_name: wyoming-snd-external-vader
          restart: unless-stopped
          ports:
            - "10602:10601"
          volumes:
            - /run/dbus:/run/dbus:ro
            - /etc/asound.conf:/etc/asound.conf:ro
          devices:
            - /dev/snd:/dev/snd
          group_add:
            - audio
          command:
            - --debug
            - --device
            - pvader
        satellite-rick:
          build: https://github.com/rhasspy/wyoming-satellite.git
          container_name: wyoming-satellite-rick
          volumes:
            - /opt/sounds:/app/extra-sounds
          ports:
            - "10700:10700"
          command:
            - "--name"
            - "Wohnzimmer Satellit Rick"
            - "--mic-uri"
            - "tcp://microphone:10600"
            - "--snd-uri"
            - "tcp://playback:10601"
            - --wake-uri
            - "tcp://openwakeword:10400"
            - --wake-word-name
            - 'hey_rick'
            - --awake-wav
            - extra-sounds/boop-852-mhz.wav
            - --done-wav
            - extra-sounds/boop-741-mhz.wav
            - --timer-finished-wav
            - extra-sounds/clock-alarm.wav
            - "--debug"
        satellite-nabu:
          build: https://github.com/rhasspy/wyoming-satellite.git
          container_name: wyoming-satellite-nabu
          volumes:
            - /opt/sounds:/app/extra-sounds
          ports:
            - "10701:10700"
          command:
            - "--name"
            - "Wohnzimmer Satellit Nabu"
            - "--mic-uri"
            - "tcp://microphone:10600"
            - "--snd-uri"
            - "tcp://playback:10601"
            - --wake-uri
            - "tcp://openwakeword:10400"
            - --wake-word-name
            - 'hey_nabu_v2'
            - --awake-wav
            - extra-sounds/boop-852-mhz.wav
            - --done-wav
            - extra-sounds/boop-741-mhz.wav
            - --timer-finished-wav
            - extra-sounds/clock-alarm.wav
            - "--debug"
        satellite-vader:
          build: https://github.com/rhasspy/wyoming-satellite.git
          container_name: wyoming-satellite-vader
          volumes:
            - /opt/sounds:/app/extra-sounds
          ports:
            - "10702:10700"
          command:
            - "--name"
            - "Wohnzimmer Satellit Vader"
            - "--mic-uri"
            - "tcp://microphone:10600"
            - "--snd-uri"
            - "tcp://vader-playback:10601"
            - --wake-uri
            - "tcp://openwakeword:10400"
            - --wake-word-name
            - 'Darth_Vader'
            - --awake-wav
            - extra-sounds/vader.wav
            - --done-wav
            - extra-sounds/g2.wav
            - --timer-finished-wav
            - sounds/timer_finished.wav
            - "--debug"
        openwakeword:
          container_name: wyoming-openwakeword
          image: rhasspy/wyoming-openwakeword
          restart: unless-stopped
          volumes:
            - /opt/wakewords:/custom
          ports:
            - "10400:10400"
          command: --preload-model jarvis_v2 --preload-model hey_rick --preload-model hey_nabu_v2 --custom-model-dir /custom --debug
          labels:
            - 'wud.tag.include=^\d+\.\d+\.\d+$$'
            - 'wud.link.template=https://github.com/rhasspy/wyoming-openwakeword/releases/tag/v$${major}.$${minor}.$${patch}'
