- name: Set configuration parameters in /boot/firmware/config.txt
  lineinfile:
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    path: /boot/firmware/config.txt
    create: yes
    state: present
    insertafter: '^\[all\]'
  with_items:
    - line: 'dwc_otg.fiq_fsm_mask=0x7'
      regexp: '^dwc_otg.fiq_fsm_mask='
    - line: 'dwc_otg.speed=1'
      regexp: '^dwc_otg.speed='
    - line: 'dtparam=audio=off'
      regexp: '^dtparam=audio='
    - line: 'dtoverlay=vc4-kms-v3d,audio=off'
      regexp: '^dtoverlay=vc4-kms-v3d'
  notify: Reboot

- name: Flush handlers
  meta: flush_handlers

- name: Install utilities
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - alsa-utils
    - pulseaudio
    - pulseaudio-utils
    - ladspa-sdk
    - swh-plugins
    - tap-plugins

- name: Disable global pulseaudio services and sockets
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: no
    scope: global
  with_items:
    - pulseaudio.service
    - pulseaudio.socket


- name: Create pulse user and add to audio group
  user:
    name: pulse
    home: /var/run/pulse
    groups: audio
    state: present
    append: yes
    shell: /usr/sbin/nologin

- name: Set real-time audio processing limits
  blockinfile:
    path: /etc/security/limits.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR AUDIO"
    block: |
      @audio   -  rtprio     99
      @audio   -  memlock    unlimited
      @audio   -  nice       -19
    
- name: Ensure autospawn is set to no in client.conf
  ansible.builtin.lineinfile:
    path: /etc/pulse/client.conf
    regexp: '^[#;]*\s*autospawn='
    line: 'autospawn=no'
    state: present

- name: Run pulseaudio.service as system service
  ansible.builtin.copy:
    dest: /etc/systemd/system/pulseaudio.service
    content: |
      [Unit]
      Description=PulseAudio system server

      [Service]
      Type=notify
      ExecStart=pulseaudio --daemonize=no --system --realtime --log-target=journal --disallow-exit --disallow-module-loading
      Restart=always
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
    owner: root
    group: root
  notify: Reload systemd

- name: Deploy daemon.conf for PulseAudio
  template:
    src: daemon.conf
    dest: /etc/pulse/daemon.conf
    mode: '0644'
  notify: Restart PulseAudio

- name: Comment out load-module module-suspend-on-idle
  ansible.builtin.replace:
    path: /etc/pulse/system.pa
    regexp: '^(load-module module-suspend-on-idle)'
    replace: '# \1'
  notify: Restart PulseAudio

- name: Comment out load-module module-detect in system.pa
  replace:
    path: /etc/pulse/system.pa
    regexp: '^(load-module module-detect)'
    replace: '# \1'
  notify: Restart PulseAudio

- name: Comment out load-module module-udev-detect in system.pa
  replace:
    path: /etc/pulse/system.pa
    regexp: '^(load-module module-udev-detect)'
    replace: '# \1'
  notify: Restart PulseAudio

- name: Add PulseAudio modules block to system.pa
  blockinfile:
    path: /etc/pulse/system.pa
    insertafter: EOF
    block: |
      load-module module-alsa-sink device=hw:0,0 rate=44100
      load-module module-alsa-source device=hw:0,0 rate=44100

      set-default-source alsa_input.hw_0_0
      set-default-sink alsa_output.hw_0_0

      #load-module module-combine-sink

      # Create the first effect sink (Pitch Shifter)
      #load-module module-ladspa-sink sink_name=pitch_shifter_sink plugin=tap_pitch label=tap_pitch control=-4,0,-90,0 channels=2

      # Create the third effect sink (Reverb) chained to the second
      #load-module module-ladspa-sink sink_name=reverb_sink sink_master=pitch_shifter_sink plugin=tap_reverb label=tap_reverb control=1500,0,-10,1,1,1,1,0 channels=2

      # Create the fourth effect sink (Compressor) chained to the third
      # load-module module-ladspa-sink sink_name=compressor_sink sink_master=reverb_sink plugin=sc4_1882 label=sc4 control=0,50,300,-20,4,2,5 channels=2

      # Create the fifth effect sink (Delay) chained to the fourth
      #load-module module-ladspa-sink sink_name=delay_sink sink_master=pitch_shifter_sink plugin=delay label=delay_5s control=0.016,0.5 channels=2

      # Create the final combined sink (vader-sink) chained to the fifth
      #load-module module-combine-sink sink_name=vader_sink slaves=delay_sink channels=2

      ### Enable Volume Ducking
      #load-module module-role-ducking trigger_roles=announce,phone,notification,event ducking_roles=any_role volume=33%
    marker: "# {mark} Managed by Ansible"
  notify: Restart PulseAudio

- name: Enable pulseaudio service
  ansible.builtin.systemd:
    name: pulseaudio.service
    enabled: yes
  notify: Restart PulseAudio

- name: Add users to pulse-access group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: pulse-access
    append: yes
  with_items:
    - root
    - daniel

- name: Copy /etc/asound.conf
  template:
    src: alsa.conf
    dest: /etc/asound.conf
  tags:
    - alsa

- name: Flush handlers
  meta: flush_handlers

- name: Ensure the destination directory exists
  file:
    path: "/opt/{{item}}/"
    state: directory
  with_items: 
    - sounds
    - wakewords

- name: Copy sound files to the host
  copy:
    src: "{{ item }}"
    dest: "/opt/sounds/{{ item | basename }}"
  with_fileglob:
    - "sounds/*"

- name: Copy wake word files to the host
  copy:
    src: "{{ item }}"
    dest: "/opt/wakewords/{{ item | basename }}"
  with_fileglob:
    - "wakewords/*"

- name: Clone the Git repository
  git:
    repo: 'https://github.com/rhasspy/wyoming-satellite.git'
    dest: /tmp/wyoming-satellite

- name: Build the Docker image
  community.docker.docker_image:
    name: wyoming-satellite
    build:
      path: /tmp/wyoming-satellite
    source: build

- name: Copy Dockerfile
  copy: src=Dockerfile dest=/tmp/wyoming-satellite-extras/

- name: Build an image from a Dockerfile
  community.docker.docker_image:
    name: wyoming-satellite-extras
    source: build
    build:
      path: /tmp/wyoming-satellite-extras/
    force_source: yes
    tag: latest

- name: Start wyoming stack
  tags: alsa
  community.docker.docker_compose_v2:
    project_name: wyoming-stack
    definition:
      version: '3.9'
      services:
        satellite-rick:
          image: wyoming-satellite-extras:latest
          restart: unless-stopped
          container_name: wyoming-satellite-rick
          volumes:
            - /opt/sounds:/app/extra-sounds
            - /run/dbus:/run/dbus:ro
            - /etc/asound.conf:/etc/asound.conf:ro
            - /var/run/pulse:/var/run/pulse
          devices:
            - /dev/snd:/dev/snd
          environment:
            PULSE_SERVER: "unix:/var/run/pulse/native"
          group_add:
            - audio
          ports:
            - "10700:10700"
          command:
            - "--name"
            - "Wohnzimmer Satellit Rick"
            - --mic-command
            - 'arecord -r 16000 -c 1 -f S16_LE -t raw'
            - --snd-command
            - 'aplay -r 22050 -c 1 -f S16_LE -t raw'
            - --wake-uri
            - "tcp://porcupine1:10400"
            - --wake-word-name
            - stachelschwein
            - --awake-wav
            - extra-sounds/boop-852-mhz.wav
            - --mic-no-mute-during-awake-wav
            - --done-wav
            - extra-sounds/boop-741-mhz.wav
            - --timer-finished-wav
            - extra-sounds/clock-alarm.wav
            - "--debug"
        satellite-nabu:
          image: wyoming-satellite-extras:latest
          restart: unless-stopped
          container_name: wyoming-satellite-nabu
          volumes:
            - /opt/sounds:/app/extra-sounds
            - /run/dbus:/run/dbus:ro
            - /etc/asound.conf:/etc/asound.conf:ro
            - /var/run/pulse:/var/run/pulse
          devices:
            - /dev/snd:/dev/snd
          environment:
            PULSE_SERVER: "unix:/var/run/pulse/native"
          group_add:
            - audio
          ports:
            - "10701:10700"
          command:
            - "--name"
            - "Wohnzimmer Satellit Nabu"
            - --mic-command
            - 'arecord -r 16000 -c 1 -f S16_LE -t raw'
            - --snd-command
            - 'aplay -r 22050 -c 1 -f S16_LE -t raw'
            - --wake-uri
            - "tcp://porcupine1:10400"
            - --wake-word-name
            - alexa
            - --awake-wav
            - extra-sounds/boop-852-mhz.wav
            - --mic-no-mute-during-awake-wav
            - --done-wav
            - extra-sounds/boop-741-mhz.wav
            - --timer-finished-wav
            - extra-sounds/clock-alarm.wav
            - "--debug"
        # satellite-darthvader:
        #   image: wyoming-satellite-extras:latest
        #   restart: unless-stopped
        #   container_name: wyoming-satellite-darthvader
        #   #profiles:
        #   #  - vader
        #   volumes:
        #     - /opt/sounds:/app/extra-sounds
        #     - /run/dbus:/run/dbus:ro
        #     - /etc/asound.conf:/etc/asound.conf:ro
        #     - /var/run/pulse:/var/run/pulse
        #   devices:
        #     - /dev/snd:/dev/snd
        #   environment:
        #     PULSE_SERVER: "unix:/var/run/pulse/native"
        #   group_add:
        #     - audio
        #   ports:
        #     - "10702:10700"
        #   command:
        #     - "--name"
        #     - "Wohnzimmer Satellit Vader"
        #     - --mic-command
        #     - 'arecord -r 16000 -c 1 -f S16_LE -t raw'
        #     - --snd-command
        #     - 'sh -c "PULSE_SINK=vader_sink aplay -r 22050 -c 1 -f S16_LE -t raw"'
        #     - --wake-uri
        #     - "tcp://openwakeword:10400"
        #     - --wake-word-name
        #     - 'Darth_Vader'
        #     - --awake-wav
        #     - extra-sounds/vader.wav
        #     - --mic-no-mute-during-awake-wav
        #     - --done-wav
        #     - extra-sounds/g2.wav
        #     - --timer-finished-wav
        #     - sounds/timer_finished.wav
        #     - "--debug"
        porcupine1:
          container_name: wyoming-porcupine1
          image: rhasspy/wyoming-porcupine1
          restart: unless-stopped
          ports:
            - "10400:10400"
          command:
            - --debug
          labels:
            - 'wud.tag.include=^\d+\.\d+\.\d+$$'
            - 'wud.link.template=https://github.com/rhasspy/wyoming-porcupine1/releases/tag/v$${major}.$${minor}.$${patch}'
        # openwakeword:
        #   container_name: wyoming-openwakeword
        #   image: rhasspy/wyoming-openwakeword
        #   restart: unless-stopped
        #   volumes:
        #     - /opt/wakewords:/custom
        #   ports:
        #     - "10401:10400"
        #   command:
        #     - --debug
        #     - "--debug-probability"
        #     - --custom-model-dir
        #     - "/custom"
        #     - --preload-model
        #     - Darth_Vader
        #   #  - --preload-model
        #   #  - hey_rick
        #   #  - --preload-model
        #   #  - hey_nabu_v2
        #   labels:
        #     - 'wud.tag.include=^\d+\.\d+\.\d+$$'
        #     - 'wud.link.template=https://github.com/rhasspy/wyoming-openwakeword/releases/tag/v$${major}.$${minor}.$${patch}'
