- name: reload netatalk
  become: yes
  service:
    name: avahi-daemon
    state: restarted
    enabled: yes
- name: reload smb
  become: yes
  service:
    name: smbd
    state: restarted
    enabled: yes
