---
- name: Reboot system
  become: true
  ansible.builtin.reboot:
    msg: Rebooting host to apply Intel GPU driver and oneAPI changes
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
