mqtt:
  host: "{{ ansible_default_ipv4.address }}"

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  mode: continuous

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

motion:
  threshold: 15
  improve_contrast: True

record:
  enabled: True
  retain:
    days: 2
    mode: motion

snapshots:
  enabled: True
  retain:
    default: 7

cameras: