mqtt:
  host: "{{ ansible_default_ipv4.address }}"

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  mode: continuous

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

cameras:
  picam: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.50.242:8554/unicast
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False
    detect:
      width: 640
      height: 480
  motioneye:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: http://192.168.50.209:8081
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 15