- name: create ha user
  user:
    name: "ha"
    groups: "users"
  register: ha_user

- name: Allow conbee with non-root user
  template:
    src: 50-ttyacm.rules
    dest: /etc/udev/rules.d/50-ttyacm.rules
    owner: root
    group: root
  notify: reload udev rules

- name: create folder config folders
  file: path={{item}} state=directory
  with_items:
  - "{{homeassistant_config_folder}}"
  - "{{nodered_config_folder}}"
  - "{{mosquitto_config_folder}}"
  - "{{mosquitto_data_folder}}"
  - "{{mosquitto_log_folder}}"

- name: Add mosquitto config
  template:
    src: mosquitto.conf
    dest: "{{mosquitto_config_folder}}/mosquitto.conf"
    owner: ha
    group: users
  # notify: reload mosquitto

- name: Checkout ha docker venv hack
  ansible.builtin.git:
    repo: 'https://github.com/tribut/homeassistant-docker-venv'
    dest: /media/Medien/home-assistant/docker
    force: yes

- name: Reposess config folders
  ansible.builtin.file:
    path: "{{item}}"
    owner: ha
    group: users
    mode: u=rwx,g=rwxs
    recurse: yes
  with_items:
  - "{{homeassistant_config_folder}}"
  - "{{nodered_config_folder}}"
  - "{{mosquitto_config_folder}}"
  - "{{mosquitto_data_folder}}"
  - "{{mosquitto_log_folder}}"

- name: Start home assistant
  community.docker.docker_compose:
    project_name: ha
    pull: yes
    definition:
      version: '3'
      services:
        homeassistant:
          container_name: homeassistant
          image: "ghcr.io/home-assistant/raspberrypi4-homeassistant:stable"
          volumes:
            - "{{homeassistant_config_folder}}:/config"
            - "{{homeassistant_config_folder}}/docker/run:/etc/services.d/home-assistant/run"
            - /etc/localtime:/etc/localtime:ro
          restart: unless-stopped
          privileged: true
          cap_add:
            - NET_RAW
            - NET_ADMIN
          network_mode: host
          devices:
            - /dev/ttyACM0
          environment:
            - PUID={{ha_user.uid}}
            - PGID={{ha_user.group}}
            - UMASK=007
            - PACKAGES=sudo libcap
        nodered:
          container_name: nodered
          image: nodered/node-red
          ports:
            - "{{nodered_http_port}}:1880"
          volumes:
            - "{{nodered_config_folder}}:/data"
          depends_on:
            - homeassistant
          environment:
            TZ: "Europe/Amsterdam"
          user: "{{ha_user.uid}}:{{ha_user.group}}"
          restart: unless-stopped
        mosquitto:
          container_name: mosquitto
          image: eclipse-mosquitto
          ports:
            - "{{mosquitto_port}}:1883"
            - "{{mosquitto_websockets_port}}:9001"
          volumes:
            - "{{mosquitto_config_folder}}/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
            - "{{mosquitto_data_folder}}:/mosquitto/data"
            - "{{mosquitto_log_folder}}:/mosquitto/log"
          restart: unless-stopped
  register: output

- #ansible.builtin.debug:
  #  var: output

- name: enable non-root ble in containenr
  community.docker.docker_container_exec:
    user: root
    container: homeassistant
    command: setcap cap_net_raw,cap_net_admin+eip /usr/local/lib/python3.9/site-packages/bluepy/bluepy-helper

- ansible.builtin.assert:
    that:
      - "output.services.homeassistant.homeassistant.state.running"
      - "output.services.mosquitto.mosquitto.state.running"
      - "output.services.nodered.nodered.state.running"

