---
- name: Dpkg-reconfigure
  listen: reconfigure locales
  ansible.builtin.command: dpkg-reconfigure locales -f noninteractive
  become: true
- name: Restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
  become: true
