- name: dpkg-reconfigure
  listen: reconfigure locales
  command: dpkg-reconfigure locales -f noninteractive
  become: yes
- name: restart systemd-journald
  service: name=systemd-journald state=restarted
  become: yes