---
- name: Create data folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
  with_items:
    - "{{ openwakeword_data_folder }}"
    - "{{ satellite_data_folder }}"

- name: Copy sound files to the host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ satellite_data_folder }}/{{ item | basename }}"
  with_fileglob:
    - "sounds/*"

- name: Copy wake word files to the host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ openwakeword_data_folder }}/{{ item | basename }}"
    mode: '0644'
  with_fileglob:
    - "wakewords/*"

- name: Clone the Git repository
  ansible.builtin.git:
    repo: "https://github.com/rhasspy/wyoming-satellite.git"
    dest: /tmp/wyoming-satellite

- name: Build the Docker image
  community.docker.docker_image:
    name: wyoming-satellite
    build:
      path: /tmp/wyoming-satellite
    source: build

- name: Copy Dockerfile
  ansible.builtin.copy:
    src: Dockerfile
    dest: /tmp/wyoming-satellite-extras/
    mode: "0644"

- name: Build an image from a Dockerfile
  community.docker.docker_image:
    name: wyoming-satellite-extras
    source: build
    build:
      path: /tmp/wyoming-satellite-extras/
    force_source: true
    tag: latest

- name: Start wyoming stack
  tags: stack
  community.docker.docker_compose_v2:
    project_name: wyoming-stack
    definition:
      networks:
        ha:
          external: true
      services:
        porcupine1:
          container_name: wyoming-porcupine1
          image: rhasspy/wyoming-porcupine1
          restart: unless-stopped
          networks:
            ha:
          ports:
            - "10400:10400"
          command:
            - --debug
          labels:
            - "wud.tag.include=^\\d+\\.\\d+\\.\\d+$$"
            - "wud.link.template=https://github.com/rhasspy/wyoming-porcupine1/releases/tag/$${major}.$${minor}.$${patch}"
        openwakeword:
          container_name: wyoming-openwakeword
          image: rhasspy/wyoming-openwakeword
          restart: unless-stopped
          networks:
            ha:
          volumes:
            - "{{ openwakeword_data_folder }}:/custom"
          ports:
            - "10401:10400"
          command:
            - --debug
            - --custom-model-dir
            - "/custom"
            - --preload-model
            - Darth_Vader
          labels:
            - "wud.tag.include=^\\d+\\.\\d+\\.\\d+$$"
            - "wud.link.template=https://github.com/rhasspy/wyoming-openwakeword/releases/tag/$${major}.$${minor}.$${patch}"
        #microwakeword:
        #  container_name: wyoming-microwakeword
        #  image: rhasspy/wyoming-microwakeword
        #  restart: unless-stopped
        #  networks:
        #    ha:
        #  ports:
        #    - "10402:10400"
        #  labels:
        #    - 'wud.tag.include=^\d+\.\d+\.\d+$$'
        #    - 'wud.link.template=https://github.com/rhasspy/wyoming-microwakeword/releases/tag/$${major}.$${minor}.$${patch}'
        whisper:
          container_name: whisper
          image: rhasspy/wyoming-whisper
          command: --model small-int8 --language de
          networks:
            ha:
          volumes:
            - "{{ whisper_data_folder }}:/data"
          environment:
            - TZ=Europe/Berlin
          restart: unless-stopped
          ports:
            - 10300:10300
        piper:
          container_name: piper
          image: rhasspy/wyoming-piper
          command: --voice de_DE-karlsson-low
          networks:
            ha:
          volumes:
            - "{{ piper_data_folder }}:/data"
          environment:
            - TZ=Europe/Berlin
          restart: unless-stopped
          ports:
            - 10200:10200

- name: Start wyoming satellites
  tags: stack
  loop: "{{ satellites }}"
  community.docker.docker_compose_v2:
    project_name: "wyoming-satellite-{{ item.name }}"
    definition:
      networks:
        ha:
          external: true
      services:
        wyoming-satellite:
          image: wyoming-satellite-extras:latest
          restart: unless-stopped
          container_name: "wyoming-satellite-{{ item.name }}"
          networks:
            ha:
          volumes:
            - "{{ satellite_data_folder }}:/app/extra-sounds"
          ports:
            - "{{ item.port }}:10700"
          command:
            - "--name"
            - "{{ item.name }}"
            - "--mic-uri"
            - "tcp://{{ hostvars['micpi'].ansible_host }}:{{ item.mic_port }}"
            - "--snd-uri"
            - "tcp://{{ hostvars['micpi'].ansible_host }}:{{ item.snd_port }}"
            - --wake-uri
            - "tcp://{{ item.wakeword_service }}:10400"
            - --wake-word-name
            - "{{ item.wake_word_name }}"
            - --awake-wav
            - "{{ item.awake_wav }}"
            - --mic-no-mute-during-awake-wav
            - --done-wav
            - "{{ item.done_wav }}"
            - --timer-finished-wav
            - "{{ item.timer_finished_wav }}"
            - --mic-auto-gain
            - "5"
            - --mic-noise-suppression
            - "2"
            #- --vad
            - "--debug"
